$(document).ready(function() {
    $.fn.datetimepicker.defaults.tooltips = {
        today: 'Bugün',
        clear: 'Seçimi temizle',
        close: 'Kapat',
        selectMonth: 'Ay Seç',
        prevMonth: 'Önceki Ay',
        nextMonth: 'Sonraki Ay',
        selectYear: 'Yıl Seç',
        prevYear: 'Önceki Yıl',
        nextYear: 'Sonraki Yıl',
        selectDecade: 'Onyıl Seç',
        prevDecade: 'Önceki Onyıl',
        nextDecade: 'Sonraki Onyıl',
        prevCentury: 'Önceki Yüzyıl',
        nextCentury: 'Sonraki Yüzyıl',
        incrementHour: 'Saati Arttır',
        pickHour: 'Saat Seç',
        decrementHour:'Saati Azalt',
        incrementMinute: 'Dakikayı Arttır',
        pickMinute: 'Dakika Seç',
        decrementMinute:'Dakikayı Azalt',
        incrementSecond: 'Saniyeyi Arttır',
        pickSecond: 'Saniye Seç',
        decrementSecond:'Saniyeyi Azalt',
    };
});
